server:
  port: 80

#服务别名----注册zookeeper到注册中心
spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: ${spring.application.name}