server:
  port: 9002

spring:
  application:
    name: cloud-nacos-server
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        #换成nginx的1111端口，做集群
        server-addr: 192.168.152.128:1111

#b暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'



