server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      label: master
      server:
        git:
          #uri: git@github.com:itcastphpgit25/springcloud-config.git
          uri: https://github.com/itcastphpgit25/springcloud-config.git
          search-paths:
           - springcloud-config
#rabbitMQ相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-config-center3344
    prefer-ip-address: true

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'


