server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      label: master
      server:
        git:
          uri: git@github.com:itcastphpgit25/microservicecloud-config.git
          search-paths:
           - microservicecloud-config


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: cloud-config-center3344
    prefer-ip-address: true

