server:
  port: 7002

spring:
  application:
    name: cloud-eureka-server7002

eureka:
  instance:
    hostname: eureka7002.com #euerka服务端的实例名称
  client:
    register-with-eureka: false #false代表不向注册中心注册自己
    fetch-registry: false #false代表自己短就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
       #单机
      #defaultZone: http://${eureka.instance1.hostname}:${server.port}/eureka/ #设置与eureka服务交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
