server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
       - id: payment_routh           #路由的ID，没有固定规则但要求唯一，建议配合服务名
         #uri: http://localhost:8001  #匹配后提供服务的路由地址
         uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
         predicates:
           - Path=/payment/get/**    #断言吗，路径相匹配的进行路由
           - After=2020-03-15T19:33:25.623+08:00[Asia/Shanghai]
           #- Cookie=username,zzyy
           #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
           #- Method:GET
           - Query=username, \d+ #要有参数名username并且值还要是整数才能路由

       - id: payment_routh2
         #uri: http://localhost:8001
         uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
         predicates:
           - Path=/payment/id/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      #注册进单节点
      defaultZone: http://localhost:7001/eureka/

#eureka:
#  instance:
#    hostname: cloud-gateway-service
#  client:
#    #表示是否将自己注册进EurekaServer默认为true
#    register-with-eureka: true
#    #是否从EurekaServer抓取自己有的注册信息 默认为true 单节点无所谓，集群必须设置为true才能配合ribbon进行负载均衡
#    fetch-registry: true
#    service-url:
#      #注册进单节点
#      defaultZone: http://localhost:7001/eureka/
#      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#  instance:
#    instance-id: cloud-gateway9527  #erueka中显示客户端的名字
#    prefer-ip-address: true  #以ip显示
